[package]
name = "headless"
version = "0.1.0"
edition = "2024"

[dependencies]
osm = { workspace = true }
map = { path = "../map" }
renderer-common = { workspace = true }
env_logger = { workspace = true }
pollster = { workspace = true }
renderer-gpu = { path = "../renderer-gpu" }
wgpu = { workspace = true }