[package]
name = "renderer-cpu"
version = "0.1.0"
edition = "2024"

[dependencies]
geo-types = { workspace = true, features = ["rstar_0_12"] }
renderer-common = { workspace = true }
glam = { workspace = true }
rustc-hash = { workspace = true }
lyon_path = { workspace = true }
lyon_algorithms = { workspace = true }
rayon = "1.12.0"
rstar = { workspace = true }
skia-safe = { workspace = true }
indexmap = { workspace = true }
