[workspace]
resolver = "3"
members = ["winit-run", "map", "app-surface", "ffi-run", "renderer-gpu", "sgnss", "renderer-cpu", "renderer-common"]

[workspace.dependencies]
app-surface = { path = "./app-surface", default-features = false }
anyhow = "1.0"
env_logger = "0.11.8"
log = "0.4.28"
pollster = "0.4.0"
winit = { version = "0.30", features = ["android-native-activity"] }
wgpu = "29.0.3"
# lower glam version is required for splines
glam = { version = "0.30.10", features = ["bytemuck"] }
num = "0.4.3"
futures-lite = "2"
raw-window-handle = "0.6"
renderer-common = { path = "renderer-common" }
lyon = "1.0.19"
lyon_path = "1.0.19"
lyon_algorithms = "1.0.19"
bytemuck = { version = "1.16", features = [ "derive" ] }
geo-types = "0.7.18"
error-stack = "0.6.0"
tokio = { version = "1", features = ["full"] }
thiserror = "2"
osm = { git = "https://github.com/ShashlikMap/shashlik-tiles-gen-v0.git" }
rand = "0.10.1"
strum = { version = "0.28", features = ["derive"] }
dotenvy = "0.15"
tiny-skia = { version = "0.12.0", default-features = false, features = ["std", "simd"] }
rustybuzz = "0.20.1"
rustc-hash = "1.1.0"
skia-safe = "0.99.0"
indexmap = "2.12.0"
crossbeam-queue = "0.3.13"
rstar = "0.12.2"

# macOS, iOS
libc = { version = "0.2", default-features = false }
objc = "0.2.7"
core-graphics-types = "0.2"

# android target
android_logger = "0.15"
jni = "0.21.1"
jni_fn = "0.1.2"
ndk-sys = "0.6"

[profile.samply]
inherits = "release"
debug = true
