[package]
name = "cpu-run"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = { workspace = true }
renderer-cpu = { path = "../renderer-cpu" }
map = { path = "../map" }
pollster = { workspace = true }
slint = { version = "1.17.0", features = ["renderer-software", "backend-linuxkms-noseat"] }
skia-safe = "0.99.0"