plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidLibrary) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.kotlinAndroid) apply false
    alias(libs.plugins.vanniktech.mavenPublish) apply false

    // Applied here (not `apply false`): BCV registers apiDump/apiCheck across subprojects.
    alias(libs.plugins.binaryCompatibilityValidator)
}

apiValidation {
    // The demo app is not published, so its surface is not a contract.
    ignoredProjects.add("composeApp")

    // uniffi bindings are generated from `ffi-run` and are an implementation
    // detail: the FfiConverter/UniffiLib scaffolding churns on every binding
    // regen and would bury real changes in the diff. Excluded until the few
    // types that leak into the public API (Point, Color, ShapeType,
    // ShashlikMapApi) are wrapped in hand-written Kotlin.
    ignoredPackages.add("uniffi.ffi_run")

    ignoredClasses.addAll(
        listOf(
            // Generated by AGP, always public, never a contract.
            "com.shashlik.kmp.shared.BuildConfig",
            // Generated by the Compose compiler for default-argument lambdas.
            "com.shashlik.kmp.ComposableSingletons\$ShashlikMapKt",
        )
    )
}

abstract class RustlsVersion : ValueSource<String, RustlsVersion.Params> {
    interface Params : ValueSourceParameters {
        val lockFile: RegularFileProperty
    }

    companion object {
        const val CRATE_NAME = "rustls-platform-verifier-android"
    }

    override fun obtain(): String {
        val version = parameters.lockFile.get().asFile.readLines().let { lines ->
            val nameIdx = lines.indexOfFirst { it.trim() == "name = \"$CRATE_NAME\"" }
            if (nameIdx < 0) {
                null
            } else {
                lines.drop(nameIdx + 1)
                    .firstOrNull { it.trimStart().startsWith("version = ") }
                    ?.substringAfter('"', "")
                    ?.substringBefore('"', "")
                    ?.takeIf { it.isNotEmpty() }
            }
        }
        return version ?: error("$CRATE_NAME not found in Cargo.lock")
    }
}

val rustlsPlatformVerifierVersion = providers.of(RustlsVersion::class.java) {
    parameters.lockFile.set(layout.projectDirectory.file("../Cargo.lock"))
}

extra["rustlsPlatformVerifierVersion"] = rustlsPlatformVerifierVersion

allprojects {
    configurations.configureEach {
        resolutionStrategy.eachDependency {
            if (requested.group == "org.rustls" && requested.name == "rustls-platform-verifier") {
                useVersion(rustlsPlatformVerifierVersion.get())
                because("native component version must be identical to version of ${RustlsVersion.CRATE_NAME}")
            }
        }
    }
}
