[package]
name = "winit-run"
version = "0.1.0"
edition = "2024"

[dependencies]
osm = { workspace = true }
map = { path = "../map" }
wgpu-canvas = { workspace = true}
env_logger = { workspace = true }
pollster = { workspace = true }
wgpu = { workspace = true}
native-dialog = "0.9.3"

slint = { git = "https://github.com/slint-ui/slint", features = ["unstable-wgpu-28"] }
log = "0.4.29"
[target.'cfg(target_os = "linux")'.dependencies]
slint = { git = "https://github.com/slint-ui/slint", features = ["backend-linuxkms-noseat", "renderer-skia-vulkan"] }
map = { path = "../map", features = ["sgnss"] }
[target.'cfg(target_os = "macos")'.dependencies]
slint = { git = "https://github.com/slint-ui/slint", features = ["backend-winit", "renderer-skia"] }

[build-dependencies]
slint-build = { git = "https://github.com/slint-ui/slint" }