[package]
name = "winit-run"
version = "0.1.0"
edition = "2024"

[dependencies]
osm = { workspace = true }
map = { path = "../map" }
wgpu-canvas = { workspace = true}
env_logger = { workspace = true }
pollster = { workspace = true }
wgpu = { workspace = true}
native-dialog = "0.9.3"

slint = { version = "1.16.0", features = ["unstable-wgpu-28"] }
[target.'cfg(target_os = "linux")'.dependencies]
slint = { version = "1.16.0", features = ["backend-linuxkms-noseat", "renderer-skia-vulkan"] }
map = { path = "../map", features = ["sgnss"] }
[target.'cfg(target_os = "macos")'.dependencies]
slint = { version = "1.16.0", features = ["backend-winit", "renderer-skia"] }

[build-dependencies]
slint-build = { version = "1.16.0" }