[package]
name = "winit-run"
version = "0.1.0"
edition = "2024"

[dependencies]
osm = { workspace = true }
map = { path = "../map" }
renderer-common = { workspace = true }
env_logger = { workspace = true }
pollster = { workspace = true }
wgpu = { workspace = true, optional = true }
strum = { workspace = true }
native-dialog = "0.9.3"
skia-safe = { workspace = true, optional = true }
renderer-cpu = { path = "../renderer-cpu", optional = true }
renderer-gpu = { path = "../renderer-gpu", optional = true }
slint = { version = "=1.17.0", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
map = { path = "../map", features = ["sgnss"] }

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { workspace = true }
slint = { version = "=1.17.0", features = ["backend-winit", "renderer-skia", "unstable-wgpu-29"] }

[features]
default = ["linux-gpu"]
linux-gpu = ["dep:slint", "dep:wgpu", "dep:renderer-gpu", "slint/unstable-wgpu-29", "slint/backend-linuxkms-noseat", "slint/renderer-skia"]
linux-cpu = ["dep:slint", "dep:skia-safe", "dep:renderer-cpu", "slint/backend-linuxkms-noseat", "slint/renderer-skia"]

[build-dependencies]
slint-build = "=1.17.0"