[package]
name = "renderer-gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true}
glam = { workspace = true }
num = { workspace = true}
wgpu = { workspace = true }
log = { workspace = true }
lyon = { workspace = true}
renderer-common = { workspace = true }
indexmap = { workspace = true }
usvg = "0.41.0"
geo-types = { workspace = true, features = ["rstar_0_12"] }
tokio = { workspace = true }
rstar = { workspace = true }
rustybuzz = { workspace = true }
rustc-hash = { workspace = true }
wesl = { version = "0.4.4", features = ["naga-ext"]}
rand = { workspace = true }
strum = { workspace = true }
splines = {  version = "5.0.0", features = ["glam"] }
image = "0.24"

[build-dependencies]
anyhow = "1.0"
wesl = { version = "0.4.4", features = ["naga-ext"]}


