// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import {
    Slider,
    GroupBox,
    HorizontalBox,
    VerticalBox,
    GridBox,
    CheckBox,
    Button,
    ComboBox,
} from "std-widgets.slint";

export enum Feature {
    SSAO,
    Shadows,
    Preview
}

export enum Action {
    DmOffice,
    Route,
    KML,
}

export component ShashlikUI inherits Window {
    in property <int> screen-width;
    in property <int> screen-height;
    in property <image> texture <=> image.source;
    out property <int> requested-texture-width: image.width / 1phx;
    out property <int> requested-texture-height: image.height / 1phx;
    property <float> prev_scale: 1.0;
    callback pointer_event(PointerEvent, float, float);
    callback vert_scroll(float);
    callback pinch(float, float, float);
    callback follow_mode(bool);
    callback feature_enabled(Feature, bool);
    callback btn_click(Action, int);
    title: "ShashlikMap";
    width: screen-width * 1phx;
    height: screen-height * 1phx;
    padding: 4px;

    HorizontalBox {
        image := Image {
            horizontal-stretch: 0.7;
            TouchArea {
                width: parent.width;
                height: parent.height;
                pointer-event(event) => {
                    pointer_event(event, self.mouse-x / 1phx, self.mouse-y / 1phx)
                }
                scroll-event(event) => {
                    vert_scroll(event.delta-y / 1phx);
                    accept;
                }
            }

            ScaleRotateGestureHandler {
                started => {
                    prev_scale = 1.0;
                }
                updated => {
                    pinch(-100.0 * (self.scale - prev_scale), self.center.x / 1phx, self.center.y / 1phx);
                    prev_scale = self.scale;
                }
            }
        }

        VerticalBox {
            horizontal-stretch: 0.3;
            CheckBox {
                text: "Follow mode";
                height: 24px;
                checked: true;
                toggled => {
                    follow_mode(self.checked)
                }
            }

            Button {
                text: "DM Office";
                height: 48px;
                clicked => {
                    btn_click(Action.DmOffice, cost.current-index)
                }
            }

            cost := ComboBox {
                height: 48px;
                model: ["pedestrian", "auto", "motorbike"];
                current-index: 0;
            }

            Button {
                text: "Route";
                height: 48px;
                clicked => {
                    btn_click(Action.Route, cost.current-index)
                }
            }

            Button {
                text: "Open KML";
                height: 48px;
                clicked => {
                    btn_click(Action.KML, cost.current-index)
                }
            }

            CheckBox {
                text: "SSAO";
                height: 24px;
                checked: false;
                toggled => {
                    feature_enabled(Feature.SSAO, self.checked)
                }
            }

            CheckBox {
                text: "Preview";
                height: 24px;
                checked: true;
                toggled => {
                    feature_enabled(Feature.Preview, self.checked)
                }
            }

            CheckBox {
                text: "Shadows";
                height: 24px;
                checked: true;
                toggled => {
                    feature_enabled(Feature.Shadows, self.checked)
                }
            }
        }
    }
}
