[package]
name = "map"
version = "0.1.0"
edition = "2024"

[features]
sgnss = ["dep:sgnss"]

[dependencies]
osm = { workspace = true }
sgnss = { path = "../sgnss", optional = true }
anyhow = { workspace = true }
renderer-common = { workspace = true }
lyon = { workspace = true}
tobj = "4.0.3"
futures = "0.3.31"
googleprojection = "1.2.0"
geo-types = { workspace = true }
log = { workspace = true }
geo = "0.33.1"
seahash = "4.1.0"
rayon = "1.11.0"
kml = { git = "https://github.com/ShashlikMap/kml" }
fast-mvt = "0.4"

glam = { workspace = true }
num = { workspace = true}

valhalla-client = { git = "https://github.com/jelmer/valhalla-client-rs", rev = "19b7f70" }

capitalize = "0.3"
# Don't use the latest version. MapTiles won't work on Android. rustls-platform-verifier still has issues.
# It's just easier not migrate yet to the latest one.
# https://github.com/rustls/rustls-platform-verifier/issues/221
reqwest = { version = "0.12.28", features = ["blocking"] }

tiles = { git = "https://github.com/ShashlikMap/shashlik-tiles", rev = "e8b0dbc" }
tokio = "1.53.1"

[build-dependencies]
anyhow = "1.0"
dotenvy = { workspace = true }

