[package]
name = "map"
version = "0.1.0"
edition = "2024"

[features]
sgnss = ["dep:sgnss"]

[dependencies]
osm = { workspace = true }
sgnss = { path = "../sgnss", optional = true }
anyhow = { workspace = true }
wgpu-canvas = { workspace = true}
lyon = { workspace = true}
tobj = "4.0.3"
futures = "0.3.31"
googleprojection = "1.2.0"
geo-types = { workspace = true }
log = { workspace = true }
geo = "0.32.0"
seahash = "4.1.0"
rayon = "1.11.0"
kml = { git = "https://github.com/ShashlikMap/kml" }
rand = { workspace = true }
fast-mvt = "0.4"

ttf-parser = "0.25.1"
glam = { workspace = true }
num = { workspace = true}

valhalla-client = "0.5.2"

capitalize = "0.3"
reqwest = { version = "0.12.24", features = ["blocking"] }

[patch.crates-io]
### 0.5.2+ doesn't work on android due to internal reqwest 0.13.0+ that uses
### rustls-platform-verifier that requires a tricky setup https://github.com/rustls/rustls-platform-verifier#android
[target.'cfg(target_os = "android")'.dependencies]
valhalla-client-android = { git = "https://github.com/jelmer/valhalla-client-rs", tag = "v0.5.0", package = "valhalla-client" }




[build-dependencies]
anyhow = "1.0"
dotenvy = { workspace = true }

