name: Publish KMP SDK
on:
  push:
    branches:
      - publish_kmp_sdk
  workflow_dispatch:

jobs:
  publish_kmp_sdk:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./kmp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            aarch64-apple-darwin
            aarch64-apple-ios
            aarch64-apple-ios-sim
            aarch64-linux-android

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Prebuild rustls-platform-verifier-android
        run: cargo build -p rustls-platform-verifier --release --target aarch64-linux-android || true

      - name: Publish to MavenCentral
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
